export enum MutationTypes {
  SET_LOADING = "SET_LOADING",
  SET_ALERT = "SET_ALERT",
  REMOVE_ALERT = "REMOVE_ALERT",
  REMOVE_ALERT_TIMEOUT = "REMOVE_ALERT_TIMEOUT",
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  REGISTRATION = "REGISTRATION",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  SET_TOKEN = "SET_TOKEN",
  GET_BOOKS = "GET_BOOKS",
  SET_BOOKS = "SET_BOOKS",
}
